packages/generator-liferay-theme/generators/app/index.js
=> fix-deprecation-prompt

packages/liferay-theme-tasks/lib/util.js, packages/liferay-theme-tasks/tasks/watch.js
=> Fixes #72 - Make watch work by using a single WatchSocket for everything

packages/liferay-theme-tasks/lib/divert/7.0/dependencies.js, packages/liferay-theme-tasks/lib/divert/common/dependencies.js
This PR will allow the dependencies array to be populated with all the
correct globs as mentioned in issue #11.
=> Fix for the theme extension bug

.travis.yml, lerna.json, package.json, yarn.lock
Related: https://github.com/liferay/liferay-themes-sdk/issues/149
=> Update lerna, and let it know that we are using Yarn workspaces

packages/liferay-theme-tasks/lib/__tests__/options.test.js, packages/liferay-theme-tasks/lib/options.js, packages/liferay-theme-tasks/package.json, packages/liferay-theme-tasks/tasks/deploy.js, packages/liferay-theme-tasks/tasks/watch.js, yarn.lock
This is another test using `http-proxy` and `tinylr` for live reloading.
Please tell me what you think when you have a chance.
Thanks!
=> Make `watch` task more robust (2nd approach)

README.md
At the moment, this is just a mirror of the README.md that I'm currently drafting in:
https://github.com/liferay/liferay-js-themes-toolkit/pull/187
Closes: https://github.com/liferay/liferay-js-themes-toolkit/issues/154
=> Provide content for top-level README.md (v8)

LICENSE.md, packages/generator-liferay-theme/LICENSE.md, packages/liferay-theme-deps-7.0/LICENSE.md, packages/liferay-theme-deps-7.1/LICENSE.md, packages/liferay-theme-deps-7.2/LICENSE.md, packages/liferay-theme-es2015-hook/LICENSE.md, packages/liferay-theme-mixins/LICENSE.md, packages/liferay-theme-tasks/LICENSE.md
Note: using "2017" as copyright date for same reasons discussed in: https://github.com/liferay/liferay-js-themes-toolkit/issues/169
Closes: https://github.com/liferay/liferay-js-themes-toolkit/issues/169
=> Add LICENSE.md files

CONTRIBUTING.md, lerna.json, package.json, yarn.lock
Full detail in the individual commit messages, but what this does is update CONTRIBUTING.md to reflect what we actually did to make the v8.0.0 release, and also removes the Lerna stuff because we didn't actually use it.
=>  Update CONTRIBUTING.md

packages/liferay-theme-tasks/tasks/watch.js
I suspect the test here has been broken since at least c15b0ed1a20fe. We were creating a "rootDir" relative to "./src" that might look like "css" or "css/partials" etc, and then comparing it against "css" instead of doing a prefix match.
The smallest fix would have been to change those `=== 'css'` style checks to `match(/^css\b/)` etc, but in the end I went with something that I hope is clearer and more readable. We add a `getResourceDir()` function that returns us a string like "css", "js" etc, and we stick with the `===` comparisons. I went with the "resource" terminology because I think "root" might be confusing here (root of what? the repo? the theme? the src directory within the theme?).
Note also that the path operations we are doing here are simpler than before. Now it's basically: …
=> Make `gulp watch` pick up changes in subdirectories (v8.x)

packages/liferay-theme-tasks/tasks/watch.js
I suspect the test here has been broken since at least c15b0ed1a20fe. We were creating a "rootDir" relative to "./src" that might look like "css" or "css/partials" etc, and then comparing it against "css" instead of doing a prefix match.
The smallest fix would have been to change those `=== 'css'` style checks to `match(/^css\b/)` etc, but in the end I went with something that I hope is clearer and more readable. We add a `getResourceDir()` function that returns us a string like "css", "js" etc, and we stick with the `===` comparisons. I went with the "resource" terminology because I think "root" might be confusing here (root of what? the repo? the theme? the src directory within the theme?).
Note also that the path operations we are doing here are simpler than before. Now it's basically: …
=> Make `gulp watch` pick up changes in subdirectories (#235)

CHANGELOG.md, CONTRIBUTING.md, scripts/changelog.js
Because I forgot to pass the "v" prefix.
=> Fix broken links in generated changelog

CONTRIBUTING.md
Mostly because I want a short list that I can click through after publishing just to make sure everything is legit.
=> Add NPM page links to CONTRIBUTING.md

scripts/changelog.js
It is too easy to produce a changelog with the wrong entries in it because one's local tags are not up to date; for example:
https://github.com/liferay/alloy-editor/pull/1219
This commit makes it harder to do that by running a `git remote update` before generation. If there is an error (say, because you are not connected to the network; unlikely, I know) or you simply want to run things more quickly, you can pass the `--no-update-tags` switch.
I also allow `--update-tags` as a switch, for symmetry, but that's the default anyway.
Test plan:
Run the generator and see this in the output:
```
Fetching remote tags: run with --no-update-tags to skip
```
Break the `git remote` command by changing it to `git remote updates` and see this instead:
```
Fetching remote tags: run with --no-update-tags …
```
=> feat: automatically prefetch tags before running changelog generator

README.md
So that people know how to create a new theme from scratch for Liferay Portal 6.2.
Closes: https://github.com/liferay/liferay-js-themes-toolkit/issues/313
=> doc: add v7 to the compatibility table (9.x) (#313)

README.md
So that people know how to create a new theme from scratch for Liferay Portal 6.2.
This is the 8.x cherry-pick of #317.
Related: https://github.com/liferay/liferay-js-themes-toolkit/issues/313
=> doc: add v7 to the compatibility table (#313)

packages/liferay-theme-tasks/lib/war_deployer.js
This is the v8.x cherry-pick of https://github.com/liferay/liferay-js-themes-toolkit/pull/322
Broken by: https://github.com/liferay/liferay-js-themes-toolkit/commit/54c57711d207a6a6612ac25adbbb3cead0e7a534#diff-b2e3a6736d0fb9f5dd8ce63552c3ea0f
=> fix: invalid "this" in deploy-live:war task (8.x)

CHANGELOG.md, packages/generator-liferay-theme/package.json, packages/liferay-theme-mixins/package.json, packages/liferay-theme-tasks/lib/devDependencies.js, packages/liferay-theme-tasks/lib/war_deployer.js, packages/liferay-theme-tasks/package.json, packages/liferay-theme-tasks/tasks/watch.js, packages/liferay-theme-tasks/test/fixtures/themes/7.2/base-theme-7-2/package.json
Just a draft PR to see CI green before tagging and publishing.
=> chore: prepare for v9.1.2 release

packages/liferay-theme-tasks/tasks/watch.js
This is the 8.x version of #358.
=> fix: prevent proxy errors from killing the watcher (8.x)

packages/liferay-theme-tasks/lib/theme_finder.js, packages/liferay-theme-tasks/lib/util.js
This is the 9.x version of #367.
Closes: https://github.com/liferay/liferay-js-themes-toolkit/issues/365
=> fix: Windows compatibility extending themes via URL (#365)

packages/generator-liferay-theme/generators/app/index.js, packages/generator-liferay-theme/generators/app/templates/src/css/custom.css, packages/liferay-theme-tasks/lib/upgrade/7.1/upgrade.js, packages/liferay-theme-tasks/tasks/upgrade.js
Closes: https://github.com/liferay/liferay-js-themes-toolkit/issues/380
=> feat: add font-awesome in upgrade process

packages/generator-liferay-theme/lib/__tests__/layout_creator.test.js, packages/liferay-theme-tasks/lib/upgrade/__tests__/upgrade.test.js, packages/liferay-theme-tasks/lib/war_deployer.js, packages/liferay-theme-tasks/tasks/watch.js, yarn.lock
This is the master/9.x version of https://github.com/liferay/liferay-js-themes-toolkit/pull/400
=> chore: update dependencies

CHANGELOG.md, packages/generator-liferay-theme/generators/layout/index.js, packages/generator-liferay-theme/package.json, packages/liferay-theme-mixins/package.json, packages/liferay-theme-tasks/lib/devDependencies.js, packages/liferay-theme-tasks/package.json, packages/liferay-theme-tasks/test/fixtures/themes/7.2/base-theme-7-2/package.json
Draft PR just to see CI green before final publishing.
=> chore: prepare v9.4.2 release

CHANGELOG.md, packages/generator-liferay-theme/generators/layout/index.js, packages/generator-liferay-theme/package.json, packages/liferay-theme-mixins/package.json, packages/liferay-theme-tasks/lib/devDependencies.js, packages/liferay-theme-tasks/package.json, packages/liferay-theme-tasks/test/fixtures/themes/7.2/base-theme-7-2/package.json
Draft PR for visibility and to see CI green one more time before actually publishing.
=> chore: prepare v9.4.3 release

README.md
Since the v9.5.0 release, we support themes for 7.3 as well.
=> docs: update version ranges in README

packages/generator-liferay-theme/package.json, packages/liferay-theme-mixins/package.json, packages/liferay-theme-tasks/package.json, scripts/release.js
Release script was failing because of CI script. We have changed the logic to make it great again.
=> chore: fix release script

packages/generator-liferay-theme/lib/util.js, packages/generator-liferay-theme/package.json, packages/liferay-theme-tasks/lib/project/gulp.js, packages/liferay-theme-tasks/package.json, packages/liferay-theme-tasks/plugin/tasks/deploy.js, packages/liferay-theme-tasks/plugin/tasks/war.js, packages/liferay-theme-tasks/theme/lib/upgrade/7.1/upgrade.js, packages/liferay-theme-tasks/theme/lib/upgrade/7.2/upgrade.js, packages/liferay-theme-tasks/theme/tasks/build/compile-css.js, packages/liferay-theme-tasks/theme/tasks/build/index.js, packages/liferay-theme-tasks/theme/tasks/build/themelets.js, packages/liferay-theme-tasks/theme/tasks/deploy.js, packages/liferay-theme-tasks/theme/tasks/watch.js, scripts/qa.js, yarn.lock
This fixes an error found during QA tests.
=> fix: #456 gulp upgrade fails with TypeError

packages/liferay-theme-tasks/README.md, packages/liferay-theme-tasks/lib/project/index.js, packages/liferay-theme-tasks/lib/project/options.js, packages/liferay-theme-tasks/lib/test/util.js, packages/liferay-theme-tasks/package.json, packages/liferay-theme-tasks/plugin/__tests__/index.test.js, packages/liferay-theme-tasks/plugin/index.js, packages/liferay-theme-tasks/plugin/tasks/deploy.js, packages/liferay-theme-tasks/plugin/tasks/version.js, packages/liferay-theme-tasks/plugin/tasks/war.js, packages/liferay-theme-tasks/theme/lib/bourbon_dependencies.js, packages/liferay-theme-tasks/theme/lib/look_and_feel_util.js, packages/liferay-theme-tasks/theme/lib/upgrade/7.1/upgrade.js, packages/liferay-theme-tasks/theme/tasks/__tests__/build.test.js, packages/liferay-theme-tasks/theme/tasks/build/compile-css.js, packages/liferay-theme-tasks/theme/tasks/build/index.js, packages/liferay-theme-tasks/theme/tasks/build/themelets.js, packages/liferay-theme-tasks/theme/tasks/deploy.js, packages/liferay-theme-tasks/theme/tasks/kickstart.js, packages/liferay-theme-tasks/theme/tasks/overwrite.js, packages/liferay-theme-tasks/theme/tasks/upgrade.js, packages/liferay-theme-tasks/theme/tasks/watch.js
Make sure all paths given from outside are assumed to be in POSIX format and use them accordingly.
See #462
=> refactor: #462 normalize paths

packages/liferay-theme-tasks/theme/lib/__tests__/theme_finder.test.js
See commit for description of PR.
=> test: remove flaky test

packages/generator-liferay-theme/lib/util.js
=> feat: warn about v10 availability

CONTRIBUTING.md
=> docs: fix release process docs

packages/liferay-theme-tasks/lib/project/index.js, packages/liferay-theme-tasks/theme/lib/bourbon_dependencies.js
See issue #485 for a description of the issue and the commit description for a description of the fix.
=> fix: #485 move temporary files out of /tmp

packages/liferay-theme-tasks/lib/prompts/url_package_prompt.js
I have copied the missing code from master following the same structure found in other prompts to make comparing code easier.
I have tested that it works manually (following the bug steps and checking the output).
=> fix: #493 make extending from URL work
