packages/generator-liferay-theme/package-lock.json, packages/generator-liferay-theme/package.json, packages/liferay-theme-finder/package.json, packages/liferay-theme-tasks/lib/theme_finder.js, packages/liferay-theme-tasks/package-lock.json, packages/liferay-theme-tasks/package.json, packages/liferay-theme-tasks/test/lib/theme_finder.js
Hey @natecavanaugh, this should fix the issues when trying to locate themes or themelets from npm registry. As far as I can tell, some dependencies needed to be updated and some APIs changed.
All tests are passing locally, we can use this to try to figure out the CI issues as well.
Finally, as yoy can see, I'm sending this to the `develop` branch. This is the git flow we're following here:
- `master` contains the code of the latest published version on npm
- `develop` contains the current work in progress
- We use a merge commit to merge into `develop`.
- When we want to release, we send a PR to `master` from `develop` and if all tests pass, then we merge and release from `master`
=> Handles inexistent npm module exception properly

packages/liferay-theme-tasks/lib/upgrade/6.2/upgrade.js, packages/liferay-theme-tasks/lib/upgrade/7.0/upgrade.js, packages/liferay-theme-tasks/lib/upgrade/__tests__/upgrade.test.js
I have sent this in a different PR because it seemed that the `rubySass` overwrite was made on purpose, so I'm not sure if this will break some other thing.
If unsure, just don't merge this PR but only [this one](https://github.com/liferay/liferay-themes-sdk/pull/40)
=> Don't overwrite rubySass setting when upgrading theme

CONTRIBUTING.md, packages/liferay-theme-tasks/README.md, packages/liferay-theme-tasks/package-lock.json, packages/liferay-theme-tasks/package.json, packages/liferay-theme-tasks/tasks/build/compile-css.js
Hey @yuchi, @sbaechler, this is an initial attempt to add PostCSS by default to the theme compilation process.
Basically, it allows you to add the following to your `package.json`:
```json
"liferayTheme": {
[...]
"postcss": [
"autoprefixer",
"postcss-modules"
],
[...]
}
```
Based on how common `autoprefixer` is, I thought we could bundle it with the tasks, so all that's needed to add this is the configuration. For other plugins, one should do `npm i postcss-modules` in their theme project.
Based on my experimentation, the range of plugins that can be used might be a bit limited, because we need to get through the SASS compilation first, and it will complain about things it doesn't understand (special syntax and so on...) so by the time the plugins get in, it will be too late.
I've tried …
=> Fixes #46 - Documents postcss option

packages/generator-liferay-theme/generators/app/__tests__/index.test.js, packages/generator-liferay-theme/generators/app/index.js, packages/generator-liferay-theme/generators/app/templates/_package.json, packages/generator-liferay-theme/generators/import/__tests__/index.test.js, packages/generator-liferay-theme/generators/import/templates/_package.json, packages/liferay-theme-deps-7.0/package.json, packages/liferay-theme-deps-7.1/package.json, packages/liferay-theme-es2015-hook/README.md, packages/liferay-theme-tasks/README.md, packages/liferay-theme-tasks/lib/__tests__/doctor.test.js, packages/liferay-theme-tasks/lib/__tests__/fixtures/doctor/_package.json, packages/liferay-theme-tasks/lib/__tests__/fixtures/doctor/_package_mixed_dependencies.json, packages/liferay-theme-tasks/lib/__tests__/liferay_theme_config.test.js, packages/liferay-theme-tasks/lib/__tests__/options.test.js, packages/liferay-theme-tasks/lib/doctor.js, packages/liferay-theme-tasks/lib/options.js, packages/liferay-theme-tasks/lib/prompts/__tests__/extend_prompt.test.js, packages/liferay-theme-tasks/lib/upgrade/__tests__/upgrade.test.js, packages/liferay-theme-tasks/package.json, packages/liferay-theme-tasks/tasks/__tests__/build.test.js, packages/liferay-theme-tasks/tasks/build.js, packages/liferay-theme-tasks/tasks/build/compile-css.js, packages/liferay-theme-tasks/test/fixtures/themes/6.2/upgrade-theme/package.json, packages/liferay-theme-tasks/test/fixtures/themes/7.0/base-theme/package.json, packages/liferay-theme-tasks/test/fixtures/themes/7.0/explicit-dependency-theme/package.json, packages/liferay-theme-tasks/test/fixtures/themes/7.0/kickstart-theme/package.json, packages/liferay-theme-tasks/test/util.js
We previously had [an issue](https://github.com/liferay/liferay-themes-sdk/issues/137) for removing the ruby-sass option from the theme generator because it is no longer required on Windows (which was the reason it was initially added).
In preparation for the next major release we remove the remaining traces of it. There is still one indirect reference to it in the form of a transitory dependency, as reported by `yarn why gulp-ruby-sass`:
```
=> Found "gulp-ruby-sass@2.1.1"
info Reasons this module exists
- "_project_#liferay-theme-tasks#liferay-theme-deps-6.2" depends on it
- Hoisted from "_project_#liferay-theme-tasks#liferay-theme-deps-6.2#gulp-ruby-sass"
```
This was added in 7b833e937500bc3e7339ec1b3eb24 ("Adds liferay-theme-deps-6.2 dependency to support upgrading from 6.2 with the …
=> Remove rubySass

packages/liferay-theme-finder/__tests__/find.test.js, packages/liferay-theme-finder/__tests__/name.test.js, packages/liferay-theme-finder/index.js, packages/liferay-theme-finder/package.json, yarn.lock
As we're not using Babel or polyfills in here at the moment, I tried to keep this pretty squarely within ES5-land; please let me know if I missed anything. There were some arrow functions in the code already on the test side, but I don't think I added any outside the tests. I am using a `Set` in one place, which is officially ES6; we could easily get away with just using an array there (we're doing intersection of tiny arrays).
Related: https://github.com/liferay/liferay-themes-sdk/issues/141
=> Remove lodash from liferay-theme-finder

packages/generator-liferay-theme/lib/divert/index.js, packages/liferay-theme-tasks/lib/divert/common/kickstart_prompt_helpers.js, packages/liferay-theme-tasks/lib/divert/index.js, packages/liferay-theme-tasks/tasks/deploy.js
Also worth noting: these two modules are almost exact duplicates. As a follow-up I am going to look at de-duping them.
Related: https://github.com/liferay/liferay-themes-sdk/issues/141
=> Remove _.isPlainObject calls in divert.js (x2)

packages/liferay-theme-deps-normalize/index.js
Before this commit, when you created a new 7.1 (or 7.2) theme, you would see this warning in the console:
Unable to add inject tags to /Users/greghurrell/code/liferay-themes-sdk/zzz-theme/node_modules/liferay-frontend-theme-unstyled/templates/portal_normal.vm
This sounds like an error, but it's totally expected because the theme in 7.1 doesn't have any Velocity templates.
So, this commit reworks things so that you just see non-scary status messages instead.
In 7.1+ you see:
Completed tag injection for node_modules/liferay-frontend-theme-unstyled/templates/portal_normal.ftl
Skipping tag injection for node_modules/liferay-frontend-theme-unstyled/templates/portal_normal.vm (does not exist)
In 7.0 you see:
Completed tag injection for …
=> Remove scary warnings from normalize process in the generator

packages/liferay-theme-tasks/lib/bourbon_dependencies.js, packages/liferay-theme-tasks/lib/divert/7.0/dependencies.js, packages/liferay-theme-tasks/lib/divert/7.0/kickstart_prompt_helpers.js, packages/liferay-theme-tasks/lib/divert/common/dependencies.js, packages/liferay-theme-tasks/tasks/build/compile-css.js, yarn.lock
We go a combination of `divert` (which dynamically selects a version-specific module) and the exported `getDependencyName` functions to generated what is essentially a fixed set of names and which is unlikely to ever change. As such it is unnecessary complexity that we can always add back in if we ever need it, but I think it's unlikely we ever will.
Extracted this out as a relatively uncontroversial bit from:
https://github.com/liferay/liferay-themes-sdk/pull/174
Test plan: `yarn test`
=> Remove unnecessary dynamism of getDependencyName

packages/generator-liferay-theme/README.md, packages/generator-liferay-theme/generators/app/index.js
If you try to generate a theme without a globally installed copy of gulp you'll get `Error: spawn gulp ENOENT` at the end. We do tell people (in the README) to install gulp globally, but that shouldn't be necessary: it is already a dependency of the generator and we can just use the generator's copy.
Test plan: `yo ./packages/generator-liferay-theme` without a globally installed copy of `gulp` and see it work without blowing up.
Closes: https://github.com/liferay/liferay-themes-sdk/issues/172
=> Remove generator dependence on globally installed gulp instance (#172)

packages/generator-liferay-theme/generators/app/index.js, packages/generator-liferay-theme/generators/app/templates/_package.json, packages/liferay-theme-tasks/lib/lookup/dependencies.js
When I ported us from `divert()` to `lookup()` in #179 I didn't change the string concatenation because I didn't want to change too many things at once.
Here as a follow-up I'm replacing it with `JSON.stringify()`. I'm not totally convinced by this change though. While we got rid of the concatenation (yay!), we now have this `split()`/`join()`/`replace()` song and dance to get the outputted JSON looking exactly how we want it. If we didn't care about that we could just leave all that off.
Anyway, going to put this up as an RFC anyway and see.
Test plan: `yarn test`, use `yo ./packages/generator-liferay-theme` to create a new theme and then inspect that the package.json is correct, including the tabs.
=> Don't use string-concatenation to build up devDependencies

package.json, packages/generator-liferay-theme/package.json, packages/liferay-theme-tasks/package.json, yarn.lock
Pushing this one as a draft because I don't want it to merge until https://github.com/liferay/liferay-themes-sdk/pull/181 goes in (I'm basing it off that, and I don't want a merge conflict).
1. Upgrade "easy" dependencies with `yarn upgrade-interactive`.
2. Upgrade "jest", which drops us from 204 vulnerabilities to 142 vulnerabilities.
I'll continue in the meantime as I wait for #181 to merge, at which point I'll rebase.
Related: https://github.com/liferay/liferay-themes-sdk/issues/97
=> Address security issues reported by "yarn audit"

README.md, package.json, packages/generator-liferay-theme/package.json, packages/liferay-theme-deps-7.0/package.json, packages/liferay-theme-deps-7.1/package.json, packages/liferay-theme-deps-7.2/package.json, packages/liferay-theme-es2015-hook/package.json, packages/liferay-theme-mixins/package.json, packages/liferay-theme-tasks/package.json
If we end up actually relocating the repo itself, there are a bunch of URLs that we should probably update too, as per:
https://help.github.com/en/articles/renaming-a-repository
Related: https://github.com/liferay/liferay-themes-sdk/issues/185
=> Rename SDK reference to "toolkit"

packages/generator-liferay-theme/generators/layout/index.js
In testing https://github.com/liferay/liferay-js-themes-toolkit/pull/192 I noticed that our post-install gulp task was bombing out after creating a new layout. I went back and established that the same is happening on current "master", due to this change: https://github.com/liferay/liferay-js-themes-toolkit/pull/173
Testing the previous release (v8.0.0-rc.3) confirms that this was a regression.
The way it used to work was that the post-install would run in the directory of the just-generated layout, and the generated gulpfile in that directory pulls in "liferay-plugin-node-tasks" and runs "init".
In the buggy "master" branch, however, we were instead running "init" from "liferay-js-themes-toolkit" (AKA "liferay-themes-sdk"); that is fine for generated themes, but not for generated theme …
=> Fix post-install for layout generator

packages/generator-liferay-theme/generators/app/index.js, packages/generator-liferay-theme/generators/app/templates/_package.json, packages/generator-liferay-theme/generators/import/index.js, packages/generator-liferay-theme/generators/layout/index.js, packages/generator-liferay-theme/generators/themelet/index.js, packages/generator-liferay-theme/package.json, yarn.lock
This is a "backport" from https://github.com/liferay/liferay-js-themes-toolkit/pull/192 which targets the master branch (v8 of the toolkit) instead of the one that that PR targets (v9 of the toolkit).
I had to redo it substantially, as well as upgrade the "import" generator (which doesn't even exist in the v9 branch, because that one is for import Liferay Portal 6.2 themes).
Major changes between version v0.18.0 and v3.2.0 of yeoman-generator:
- You `extend` the base `Generator` class now instead of using objects.
- This in turn means that the `_.cloneDeep` and `_.merge` stuff that we were doing now to base the layout and themelet generators off of the main "app" generator no longer works. As an alternative, I extracted out the sub-methods that were in the "priority" objects and turned …
=> Update yeoman-generator v0.18.0 to 3.2.0 (for v8 of toolkit)

README.md, package.json, packages/generator-liferay-theme/package.json, packages/liferay-theme-deps-7.0/package.json, packages/liferay-theme-deps-7.1/package.json, packages/liferay-theme-deps-7.2/package.json, packages/liferay-theme-es2015-hook/package.json, packages/liferay-theme-mixins/package.json, packages/liferay-theme-tasks/package.json
I already did this for v9 in:
https://github.com/liferay/liferay-js-themes-toolkit/pull/187
But as we are going to cut at least one last v8 release, we should rename it there too.
Related: https://github.com/liferay/liferay-js-themes-toolkit/issues/185
=> Update references to old repository name (v8)

packages/generator-liferay-theme/generators/app/index.js, packages/generator-liferay-theme/generators/themelet/index.js
This is a regression that I most likely introduced in:
https://github.com/liferay/liferay-js-themes-toolkit/pull/195
The v9 version of the same:
https://github.com/liferay/liferay-js-themes-toolkit/pull/187
doesn't have the same bug because it uses a different workaround, but I like the one used in this commit better so I am going to propagate it over there too.
Basically, we can't call `lookup` to get the `devDependencies` when making an "All" versions themelet, and we don't have to anyway, because the generated "package.json" does not have a "devDependencies" property in any case.
Test plan:
- `yarn test`
- `yo ./packages/generator-liferay-theme/generators/themelet`
- `yo ./packages/generator-liferay-theme/generators/import`
- `yo ./packages/generator-liferay-theme/generators/layout`
- …
=> Fix "packageVersion is not defined" generator an "All" themelet

packages/liferay-theme-deps-7.0/LICENSE.md, packages/liferay-theme-deps-7.1/LICENSE.md, packages/liferay-theme-deps-7.2/LICENSE.md
I had removed these deps packages in de2245d06570466, 78257a00ef30fd3, and dc7e88bf1c7bda but they snuck, partially, back into existence in the big merge commit (2137622d7a30) done before merging the initial batch of v9 work (#187).
Let's kill them again.
=> Clean out packages directory

packages/generator-liferay-theme/generators/common/messages.js, packages/generator-liferay-theme/package.json, packages/liferay-theme-mixins/package.json, packages/liferay-theme-tasks/lib/lookup/dependencies.js, packages/liferay-theme-tasks/package.json, packages/liferay-theme-tasks/test/fixtures/themes/7.2/base-theme-7-2/package.json
We cut the v8.0.0 final release earlier this morning, so we can do two things here:
1. Update the prompt in "common/messages.js" telling people how to install v8 to reference "8.0.0" instead of "8.0.0-rc.3", which was the previous release.
2. Bump the package numbers: note that we aren't actually publishing the release yet, but I think we should bump the numbers in preparation because it is a bit weird to have numbers in "master" that are older than the current release.
Related: https://github.com/liferay/liferay-js-themes-toolkit/issues/225
=> Bump version numbers in preparation for first v9 release

packages/liferay-theme-tasks/lib/devDependencies.js
These were published just yesterday. They also have an implicit dependency on "liferay-frontend-common-css" so I added that back to the list.
Related: https://github.com/liferay/liferay-js-themes-toolkit/issues/225
=> Update dependencies to point at new snapshots

scripts/changelog.js
When I used this earlier today I forgot to use a "v" prefix when I specified the version number. This change makes the tool a little more foolproof by warning you if you forget, and adding it on for you (you can disable the autocorrection and force it to do what you say anyway with `--force`).
In this repo we always use the "v" prefix but we might not in others, and I am anticipating using this script in other places, so instead of hard-coding a check for a "v" prefix, what this actually does is look at the existing tags and decides whether "v" is used by convention. If it is not, it actually behaves in the inverse manner: it warns about an *unexpected* "v" prefix and automatically removes it, unless you use `--force`.
The nested `if`/`else`/`else if` is horrid, but that is the price one …
=> Teach the changelog generator to correct errors with "v" prefix

package.json
Similar to other projects where we have "lint" and "lint:fix" scripts, because "yarn lint:fix" is ever so slightly easier to type than "yarn lint --fix".
=> Add lint:fix script as a convenience

packages/liferay-theme-tasks/lib/doctor.js
While trying to reproduce:
https://github.com/liferay/liferay-js-themes-toolkit/issues/244
you can see how if you run the "import" generator to import a 6.2 theme and then run "gulp build" you will see this unfriendly error message:
> Error: Task 'build' is not supported for themes with version '6.2' in
> this version of 'liferay-theme-tasks'
In our docs, we advise people to run "gulp upgrade" first:
https://dev.liferay.com/en/develop/tutorials/-/knowledge_base/7-1/running-the-upgrade-task-for-6-2-themes
But people may not read the docs, so let's improve the error message as well. With this commit, we instead say:
> Error: Task 'build' is not supported for themes with version '6.2'
> in this version of 'liferay-theme-tasks' - please run "gulp upgrade"
> first
Test plan: `yarn test`, and …
=> Provide a hint to run "gulp upgrade" before "build" after import

packages/liferay-theme-tasks/package.json, yarn.lock
I had mistakenly removed the gulp-prompt dependency in bea3c7035673e80 because I thought it was unused and the old version (0.1.2) was adding noise to the `yarn audit` report.
Turns out it still is used by the 6.2 "upgrade" task, but the usage didn't show up in my search because there is no explicit `require()` call, only dynamic loading via the "gulp-load-plugins" package. (And now that I look at the list of plugins in the theme tasks package.json, I see some others that I suspect may not be used anywhere, but auditing those must be a task for a different commit.)
Here we add it back, but now a much newer version (1.2.0). The `yarn audit` output is unaffected.
Test plan: `gulp upgrade` in a 6.2 theme ([gist](https://gist.github.com/wincent/30a1cad30e6c92b9d9c05a067c019ddc)); `yarn test`. …
=> Fix "gulp upgrade" task for 6.2 themes (#244)

packages/generator-liferay-theme/generators/import/index.js
This is a follow-up to #246. We found in testing that relative paths worked inside the current working directory, but a path like "../my-theme" did not. I believe this commit truly makes things work in a path-agnostic way.
Here's what was happening before when you ran the generator:
1. In the "import" generator, `this.appname` would be set to the basename of the supplied theme. In other words, irrespective of whether you passed "./my-theme", "../my-theme", "my-theme" or "/abs/path/my-theme" it would be set to "my-theme".
2. In the "base" class, `_setThemeDirName` would set `this.themeDirName` to "my-theme"; if you had instead passed "my" (and a folder with that name existed on disk) then `themeDirName` would become "my-theme" at that point.
3. In the "base" class, `_enforceFolderName` …
=> Make theme importing work regardless of theme location

packages/generator-liferay-theme/generators/import/index.js
In discussing the related ticket it became clear that the new behavior of the tool was not intended: we were performing an in-place update of an imported theme instead of creating a new theme folder in the current directory.
I added some comments to the code to make it clear what is actually happening.
Test plan:
1. With a 6.2 theme one directory above us, do `yo path/to/generator` and supply "../manzanita-theme" as a path. See the new theme get created in the current directory with name "manzanita-theme".
2. With a 7.2 theme one directory below us, do `yo path/to/generator` and supply "/absolute/path/to/manzanita" as a path. See the theme get created in the current directory with name "manzanita-theme" (note that it appended "-theme" even though I had intentionally stripped that suffix …
=> fix: "import" generator performing in-place imports

packages/liferay-theme-tasks/lib/doctor.js
Test plan:
In a 7.1 theme gulpfile, change the `require` to point at this PR (ie. `require('../packages/liferay-theme-tasks')`.
Then, run `gulp upgrade` in the 7.1 theme and see:
Error: Task 'upgrade' is not supported for themes with
version '7.1' in this version of 'liferay-theme-tasks' -
to upgrade a 7.1 theme please run "npm install --save-dev
liferay-theme-tasks@9.0.0-alpha.1" and then "gulp upgrade" again
Run `npm install --save-dev liferay-theme-tasks@9.0.0-alpha.1`. Change the `require` back to `require('liferay-theme-tasks')` so that the theme will use the code we just told the user to download, then run `gulp upgrade` again and see it work.
Note that users obviously won't have to edit their gulpfiles; it's only necessary for testing in a dev environment like this one.
Closes: …
=> feat: Provide hint to update to v9.x in order to upgrade a 7.1 theme

packages/liferay-theme-tasks/lib/doctor.js
As noted in the related issue, in a couple of recent PRs I taught `doctor.js` to provide a helpful hint instead of just blowing up when you try to perform a task that is not supported for a particular theme version. For example you would see a message like:
Error: Task 'upgrade' is not supported for themes with version '7.1'
in this version of 'liferay-theme-tasks' - please run
"npm install --save-dev liferay-theme-tasks@9.0.0-alpha.1"
and then "gulp upgrade" again
or:
Error: Task 'build' is not supported for themes with version '6.2'
in this version of 'liferay-theme-tasks' - please run "gulp upgrade"
first
Trouble is, this text was easy to miss because it was in the default foreground color and followed by a huge stack trace.
In this commit we instead show it on a separate line, in …
=> feat: Make "doctor" tips stand out in a different color

packages/liferay-theme-tasks/lib/upgrade/6.2/upgrade.js
While trying to repro the related issue I noticed that CSS files in the theme were not getting renamed despite me answering "y" at the prompts.
The cause was a broken test for `promptResults[fileName]`, where `fileName` was something like "custom.css". This doesn't actually match the `promptResults` data structure, which looks like this:
{
custom: {
css: true,
},
main: {
css: false,
},
}
(where the `true` and `false` values reflect the answers given at the prompts.)
Test plan:
- `yarn test`
- `yo ./packages/generator-liferay-theme/generators/import`
- Provide path to a 6.2 theme, eg. "./manzanita".
- In the imported theme, edit the gulpfile to `require('../packages/liferay-theme-tasks')` so that we can test this change.
- `gulp upgrade`.
- Answer "y" and "n" at the prompts:
```
? Do you …
```
=> fix: failure to rename css -> scss files during 6.2 -> 7.0 upgrade (#265)

packages/generator-liferay-theme/README.md
Apparently, Visual Studio is no longer required, just node-gyp (and therefore Python). I removed the references, and also removed some of the regretful emotional wording in favor of a more neutral register.
Closes: https://github.com/liferay/liferay-js-themes-toolkit/issues/271
=> doc: remove stale references to Visual Studio (#271)

scripts/changelog.js
Two things:
- Make sure we autodetect `git@github.com` remotes, which means we'll be less likely to run the command twice in a row (once without and once with the `--remote` switch).
- Make the "already contains reference to $VERSION" warning into a hard error, unless running with `--force`.
=> fix: make it harder to accidentally produce duplicate entries in changelog

packages/liferay-theme-tasks/tasks/watch.js
We used to print something like:
```
[Browsersync] Proxying: http://localhost:8080
[Browsersync] Access URLs:
---------------------------------
Local: http://localhost:9080
External: http://192.168.2.3:9080
```
when you started watch mode. Now we print pretty much nothing, just some Gulp output ending with:
```
[10:09:22] Starting 'watch:setup'...
[10:09:23] Finished 'watch:setup' after 686 ms
```
While it's true that we do open a browser window pointing at the right port, we should probably also log the URL to the console.
Test plan: Run `gulp watch` and see:
```
[11:00:18] Finished 'build' after 4.31 s
[11:00:18] Starting 'watch:clean'...
[11:00:19] Finished 'watch:clean' after 239 ms
[11:00:19] Starting 'watch:setup'...
[11:00:19] Finished 'watch:setup' after 710 ms …
```
=> feat: print watch info when starting watch (#277)

packages/liferay-theme-tasks/tasks/watch.js
This is the v8.x cherry-pick of:
https://github.com/liferay/liferay-js-themes-toolkit/pull/278
We used to print something like:
```
[Browsersync] Proxying: http://localhost:8080
[Browsersync] Access URLs:
---------------------------------
Local: http://localhost:9080
External: http://192.168.2.3:9080
```
when you started watch mode. Now we print pretty much nothing, just some Gulp output ending with:
```
[10:09:22] Starting 'watch:setup'...
[10:09:23] Finished 'watch:setup' after 686 ms
```
While it's true that we do open a browser window pointing at the right port, we should probably also log the URL to the console.
Test plan: Run `gulp watch` and see:
```
[11:00:18] Finished 'build' after 4.31 s
[11:00:18] Starting 'watch:clean'...
[11:00:19] Finished 'watch:clean' after 239 ms …
```
=> feat: print watch info when starting watch (v8.x) (#277)

CHANGELOG.md, README.md, packages/generator-liferay-theme/generators/common/messages.js
Updates the references in the README and CHANGELOG just like we did for 8.x in: https://github.com/liferay/liferay-js-themes-toolkit/pull/282
Additionally, there is a change in the generator output, which is what led us to create this issue in the first place. (cc: @mwilliams2014).
Test plan: `yarn test` and run the generator with `yo ./packages/generator-liferay-theme` and see:
This version of the liferay-js-themes-toolkit (9.0.0-alpha.1)
can create a liferay-theme for Liferay DXP and Portal CE v7.2
For older versions, please use v8 of the toolkit:
npm i -g generator-liferay-theme@^8.0.0
yo liferay-theme
Closes: https://github.com/liferay/liferay-js-themes-toolkit/issues/280
=> chore: Update references to "DXP" in user-facing messages (9.x) (#280)

packages/liferay-theme-tasks/package.json, packages/liferay-theme-tasks/tasks/build.js, packages/liferay-theme-tasks/tasks/build/compile-css.js, yarn.lock
When deploying a theme using this config in the package.json:
"liferayTheme": {
"baseTheme": "styled",
"distName": "fjord-theme",
"rubySass": false,
"version": "7.1",
"postcss": [
"autoprefixer"
]
},
the deploy would silently fail because "gulp-plumber" would swallow the error. If I am reading this background material on plumber correctly:
- https://github.com/floatdrop/gulp-plumber
- https://github.com/gulpjs/gulp/issues/91
- https://gist.github.com/floatdrop/8269868
the intent of the plug-in is to monkey patch the Gulp pipe objects such that an error in one file won't prevent the others from being processed. We added it in this repo in commit 9200922420ee2c290c7d8f658551 (Jan 2016, "Use gulp-plumber for r2 task so that sass-parse errors don't abort build process").
In practice, its …
=> fix: silent failures when using autoprefixer (9.x) (#274)

packages/liferay-theme-tasks/package.json, packages/liferay-theme-tasks/tasks/build.js, packages/liferay-theme-tasks/tasks/build/compile-css.js, yarn.lock
This is the 8.x equivalent of #287.
When deploying a theme using this config in the package.json:
"liferayTheme": {
"baseTheme": "styled",
"distName": "fjord-theme",
"rubySass": false,
"version": "7.1",
"postcss": [
"autoprefixer"
]
},
the deploy would silently fail because "gulp-plumber" would swallow the error. If I am reading this background material on plumber correctly:
- https://github.com/floatdrop/gulp-plumber
- https://github.com/gulpjs/gulp/issues/91
- https://gist.github.com/floatdrop/8269868
the intent of the plug-in is to monkey patch the Gulp pipe objects such that an error in one file won't prevent the others from being processed. We added it in this repo in commit 9200922420ee2c290c7d8f658551 (Jan 2016, "Use gulp-plumber for r2 task so that sass-parse errors don't abort …
=> fix: silent failures when using autoprefixer (8.x) (#274)

packages/liferay-theme-tasks/lib/util.js, packages/liferay-theme-tasks/package.json, packages/liferay-theme-tasks/tasks/build/compile-css.js
Prior to this commit, we would look at the plugins named in the theme's "package.json" file under "liferayTheme" -> "postcss" and load them. "autoprefixer" was whitelisted because we bundle it with liferay-theme-tasks (ie. we would just do `require('autoprefixer')`).
For the others we would go through our `resolveDependency` helper, which actually seems to be a pointless in the context of PostCSS. I'm going to remove that special casing in the next commit, in order to make it easier to review.
With this commit, we allow for configuration by any of the mechanisms supported by postcss-load-config:
https://www.npmjs.com/package/postcss-load-config
(gulp-postcss will use postcss-load-config transparently behind the scenes).
What this means is that you can add a "postcss" property to you …
=> feat: add ability to config PostCSS plug-ins (9.x) (#126)

packages/liferay-theme-tasks/lib/util.js, packages/liferay-theme-tasks/package.json, packages/liferay-theme-tasks/tasks/build/compile-css.js
This is the v8.x version of https://github.com/liferay/liferay-js-themes-toolkit/pull/289 — see that one for all the details, or read the individual commit messages.
I just cherry-picked the commits over: the one thing that was different is the `resolveDependency()` change, because the branches have diverged a bit on that one.
=> feat: add ability to config PostCSS plug-ins (8.x) (#126) 

README.md
At the time I wrote the table, I thought we were going to use Gulp v3 in version 8 and Gulp v4 in version 9, but in the end we stayed with Gulp v3 in both, so we should remove it from the table to avoid confusion. (I already removed the reference to v4 in 9c66f058ffee7).
=> doc: remove Gulp entry from version table (v8.x)

README.md
At the time I wrote the table, I thought we were going to use Gulp v3 in version 8 and Gulp v4 in version 9, but in the end we stayed with Gulp v3 in both, so we should remove it from the table to avoid confusion. (I already removed the reference to v4 in 7a6da6568894f3).
=> doc: remove Gulp entry from version table (v9.x)

packages/liferay-theme-tasks/README.md, packages/liferay-theme-tasks/lib/__tests__/options.test.js, packages/liferay-theme-tasks/lib/options.js, packages/liferay-theme-tasks/lib/prompts/extend_prompt.js, packages/liferay-theme-tasks/lib/util.js, packages/liferay-theme-tasks/plugin/lib/options.js, packages/liferay-theme-tasks/plugin/test/index.js, packages/liferay-theme-tasks/tasks/build/compile-css.js
If supplied, this comma-separated list of include paths with be appended to the list of search paths provided to Sass. Relative paths are considered to be relative to the current working directory.
Closes: https://github.com/liferay/liferay-js-themes-toolkit/issues/305
=> feat: teach theme tasks to accept --sass-include-paths option (#305)

packages/liferay-theme-tasks/tasks/watch.js
Our "watch" proxy was breaking the sign-in flow, CSS, and possibly other things that we don't know about yet because it was pre-pending the "livereload" script tag where it shouldn't go, instead at the end of the HTML response.
Closes: https://github.com/liferay/liferay-js-themes-toolkit/issues/309
Closes: https://github.com/liferay/liferay-js-themes-toolkit/issues/310
=> fix: broken CSS and sign-in when using "watch" proxy (#309, #310)

packages/liferay-theme-tasks/tasks/watch.js
This is the v8 cherry-pick of the corresponding "master"/v9.x fix (#312).
I'll attach a screenshot showing me testing this with the 7.1 community binary.
=> fix: broken CSS and sign-in when using "watch" proxy (8.x) (#309, #310)

packages/liferay-theme-tasks/tasks/watch.js
Our watch mode was choking horribly trying to join a string onto gzipped content, causing the result page to be a garbled mess.
Test plan: Launch portal in production mode (ie. with GZipFilter turned on) and connect to proxy port (9080). See the request headers show: "Accept-Encoding: gzip", but server returns no "Content-Encoding: gzip"; now connect on non-proxy port (8080) and see "Content-Encoding: gzip". In both cases, page renders correctly.
Proxied headers:
Non-proxied headers:
Closes: https://github.com/liferay/liferay-js-themes-toolkit/issues/311
=> fix: make "watch" mode work with portal gzipped (#311)

packages/liferay-theme-tasks/tasks/watch.js
At the moment, we are [buffering the response](https://github.com/liferay/liferay-js-themes-toolkit/blob/8ed39dec06a0467b4/packages/liferay-theme-tasks/tasks/watch.js#L225-L227) that our proxy gets back from the upstream Liferay instance, because I copied [the example in the node-http-proxy docs](https://github.com/nodejitsu/node-http-proxy/#modify-response). 
In reality we don't need to buffer and can instead pass it directly on, which should make the watch mode more responsive.
Test plan: Create a new theme with `yo ./packages/generator-liferay-theme`, deploy and watch it by `cd`-ing into the generated theme and running `gulp watch`. Inspect network response and see live reload tag is appended at end, live reloading works when you edit an SCSS file, and all other resources continue to …
=> perf: avoid unnecessary buffering of responses in watch mode (#324)

scripts/changelog.js
As noted in #334 we accidentally created a lightweight (ie. non-annotated) tag in the AlloyEditor project, which lead the changelog script to not "see" the previous release tag, seek to the one prior to that, and thus include some duplicate entries in the changelog.
We can avoid that by passing the `--tags` switch to `git describe`, but I'll also add a check in AlloyEditor to make sure we don't accidentally create non-annotated tags in the future.
Closes: https://github.com/liferay/liferay-js-themes-toolkit/issues/334
=> feat: handle lightweight tags in changelog script

packages/liferay-theme-tasks/lib/upgrade/__tests__/upgrade.test.js, packages/liferay-theme-tasks/tasks/upgrade.js
We have functionality that creates a backup of files before attempting an upgrade and then offer a revert functionality in the case that an error is thrown.
In practice, this isn't as good as proper version control because:
- You cannot "double revert" because we only make a backup of the most recent change.
- In the event that an upgrade fails we blow away the upgraded files by doing an automatic revert, preventing the user from inspecting them.
- We incur complexity in the codebase, opening the door to bugs.
- We can't provide a very nice upgrade-and-revert experience moving from 6.2 to 7.0 to 7.1 to 7.2 and back because those moves involve switching versions of the toolkit from v8 to v9 along the way, as described in #267.
So this commit removes the backup and revert functionality and …
=> chore: remove backup/revert functionality (9.x) (#267)

packages/liferay-theme-tasks/lib/devDependencies.js
Test plan: `yarn ci`; generate a theme with `yo ./packages/generator-liferay-theme`, inspect generated "package.json" and "node_modules" folder, see the requested versions have been included, `gulp deploy` the theme and see it work in running liferay-portal instance.
Closes: https://github.com/liferay/liferay-js-themes-toolkit/issues/341
=> chore: Update theme dependencies for Liferay 7.2 release (#341)

packages/liferay-theme-tasks/index.js, packages/liferay-theme-tasks/lib/checkNodeVersion.js
This should help people who run into issues like #339 where things aren't working due to an old NodeJS version. Now, we'll print a warning that they should upgrade, but we'll still try to run.
Test plan: In a generated theme with the gulpfile.js `require` pointing at my local "liferay-theme-tasks" repo, run `gulp --tasks` and see no warning. Then tweak the `REQUIREMENTS` to fail and run `gulp --tasks` again and see a warning.
Closes: https://github.com/liferay/liferay-js-themes-toolkit/issues/339
=> feat: add a runtime NodeJS version check (#339)

packages/liferay-theme-tasks/tasks/build/compile-css.js, packages/liferay-theme-tasks/tasks/watch.js
For non-CSS/JS changes, we call the "deploy" task, and the first thing that does is "build", and the first thing that does is "clean", which deletes the CSS.
We then had a short-circuit that skipped over compiling SCSS to CSS if the file that triggered the change wasn't a CSS file. Then when "watch:reload" reloads the window, we can't deliver the CSS (it was deleted and not rebuilt), so we send a 404 instead and everything is horribly broken.
The fix then is to remove the shortcircuit, because it is better to be a slower-but-working than faster-and-broken.
I kept the old task around even though it reduces to an empty layer of indirection, in the name of backwards compatibility.
Test plan: `gulp watch` in a theme and make edits to CSS and ".ftl" files.
Closes: …
=> fix(tasks): non-CSS/JS file changes break CSS when using "watch" (#340)

packages/liferay-theme-tasks/tasks/watch.js
Fixes #349.
Test plan:
* Run `gulp watch`
* Run `curl -I http://localhost:9080/o/theme-name/js/main.js`
* See `Content-Type: text/javascript` in output
=> fix: Fix typo in JS MIME type (8.x) (#349)

packages/liferay-theme-tasks/tasks/watch.js
9.x version of #349 fix.
Test plan:
* Run `gulp watch`
* Run `curl -I http://localhost:9080/o/theme-name/js/main.js`
* See `Content-Type: text/javascript` in output
=> fix: Fix typo in JS MIME type (9.x) (#349)

packages/liferay-theme-tasks/lib/devDependencies.js
To guard against unintended breakages. And add a little wrapper that will blow up if we ever pass a non-strict dependency.
Closes: https://github.com/liferay/liferay-js-themes-toolkit/issues/352
=> chore: strictly peg dependency versions (#352)

CONTRIBUTING.md
Because of the way NPM works, only one package will ever get the "latest" tag in the registry, which leads to all sorts of confusing behavior. `npm install` will grab the latest (most recently published), rather than the highest semver-satisfying version. So, if we publish 9.1.4, and then 8.0.11, `npm install` will grab the 8.x release.
So, to ensure that 9.x releases are always the "latest", we need to use tags for 8.x releases.
=> docs: indicate the use of `--tag` when publishing

packages/liferay-theme-tasks/tasks/watch.js
Like is being done with the livereload server, this will handle errors on the proxy server (e.g. socket hang up due to ECONNRESET) instead of allowing them to crash the watcher.
=> fix: prevent proxy errors from killing the watcher

packages/liferay-theme-tasks/lib/prompts/__tests__/extend_prompt.test.js, packages/liferay-theme-tasks/lib/prompts/__tests__/kickstart_prompt.test.js, packages/liferay-theme-tasks/lib/prompts/__tests__/prompt_util.test.js, packages/liferay-theme-tasks/lib/prompts/extend_prompt.js, packages/liferay-theme-tasks/lib/prompts/kickstart_prompt.js, packages/liferay-theme-tasks/lib/prompts/url_package_prompt.js, packages/liferay-theme-tasks/lib/theme_finder.js
This is the v9.x ("master" branch) version of #332.
It's basically a series of totally clean cherry-picks, except for the very last "test: provide a little extra test coverage" commit, for which I had to resolve a tiny conflict.
See the original pull for related discussion.
=> feat: teach `gulp extend` to accept a package URL (9.x) (#266)

packages/liferay-theme-tasks/lib/theme_finder.js, packages/liferay-theme-tasks/lib/util.js
Two parts to this fix:
- Use `spawn.sync` from the "cross-spawn" module, which fixes the failure to find the `npm` executable on Windows.
- Don't swallow errors when spawning.
I created https://github.com/liferay/liferay-js-themes-toolkit/issues/366 separately to track the task of adding a lint to stop us from using `child_process.spawnSync` in the future.
This is the 8.x version of the fix. I'll create a separate PR for the 9.x version.
=> fix: Windows compatibility extending themes via URL (#365)

packages/liferay-theme-tasks/lib/prompts/__tests__/extend_prompt.test.js, packages/liferay-theme-tasks/lib/prompts/__tests__/kickstart_prompt.test.js, packages/liferay-theme-tasks/lib/prompts/extend_prompt.js, packages/liferay-theme-tasks/lib/prompts/kickstart_prompt.js
Based on my experience in #367, I searched for other usages of `child_process` which might not work on Windows and found these two. I believe these two `npm install` were failing on Windows as a result.
Note that we have tests asserting that errors are emitted, but they were bad, so I removed them:
1. The tests shouldn't be actually running `npm install`; they should be using stubs.
2. However, in the implementation, errors are ignored. It seems pointless to verify that an error is emitted if you are going to ignore it anyway.
Also note the useless `hideOutput` flag that nobody is ever passing.
Test plan: run `gulp extend` in a generated theme.
Related: https://github.com/liferay/liferay-js-themes-toolkit/issues/365
=> fix: silent `npm install` failures on Windows in extend and kickstart

CONTRIBUTING.md, update-package-versions-config.js
Previously we still had to do a manual update. I can't remember why right now; maybe it was a misgiving about using a potentially brittle pattern -- in any case, the whole thing is brittle so we may as well go for it and fully automate it. If it breaks, it will break.
=> feat: make `yarn updatePackageVersions` change all usages

.github/semantic.yml
I believe that the bot has now been activated for this repo, so we can do exactly what we did in:
https://github.com/liferay/liferay-frontend-guidelines/pull/70
This is the 8.x version of:
https://github.com/liferay/liferay-js-themes-toolkit/pull/385
I don't know whether the bot will respect per-branch configuration, but I can see it at least ran on the similar PR I sent for the 1.x branch in the AlloyEditor repo:
https://github.com/liferay/alloy-editor/pull/1311
=> feat: configure Semantic Pull Requests bot (8.x)

package.json, packages/generator-liferay-theme/generators/app/__tests__/index.test.js, packages/generator-liferay-theme/generators/common/messages.js, packages/generator-liferay-theme/generators/layout/__tests__/index.test.js, packages/generator-liferay-theme/generators/themelet/__tests__/index.test.js, packages/generator-liferay-theme/lib/__tests__/layout_creator.test.js, packages/liferay-theme-tasks/index.js, packages/liferay-theme-tasks/lib/look_and_feel_util.js, packages/liferay-theme-tasks/lib/war_deployer.js, packages/liferay-theme-tasks/plugin/test/fixtures/hook_modules/hook-module-1.js, packages/liferay-theme-tasks/plugin/test/index.js, packages/liferay-theme-tasks/plugin/test/lib/register_hooks.js, packages/liferay-theme-tasks/plugin/test/tasks/deploy.js, packages/liferay-theme-tasks/plugin/test/tasks/init.js, packages/liferay-theme-tasks/plugin/test/tasks/version.js, packages/liferay-theme-tasks/plugin/test/tasks/war.js, packages/liferay-theme-tasks/tasks/__tests__/build.test.js, packages/liferay-theme-tasks/tasks/build.js, packages/liferay-theme-tasks/tasks/build/themelets.js, packages/liferay-theme-tasks/test/util.js, yarn.lock
New:
- destructure-requires
- imports-first (this one was in eslint-config-liferay v10.0.0 but not turned on by default).
- no-require-and-call
=> chore: update eslint-config-liferay to v11.0.1

packages/generator-liferay-theme/generators/layout/index.js
Closes: https://github.com/liferay/liferay-js-themes-toolkit/issues/409
=> fix: correct misspelled function in layout generator (#409)

packages/generator-liferay-theme/generators/layout/index.js
`yo liferay-theme:layout` was producing `liferay-layout-templates.xml` files with bad paths like:
<template-path>\layouttpl\custom\foo-layouttpl/foo.ftl</template-path>
instead of:
<template-path>/layouttpl/custom/foo-layouttpl/foo.ftl</template-path>
leading to a runtime error on Windows when deploying.
You can see in our template files that we should always be using POSIX path separators:
https://github.com/liferay/liferay-js-themes-toolkit/blob/bdad65c47130f09193a66baad982e01f32cebd2e/packages/generator-liferay-theme/generators/layout/templates/docroot/WEB-INF/liferay-layout-templates.xml#L7-L8
Ideally this regression(?) would have been caught by our test suite, but the related functional tests are disabled right now and have been since c3c4e9a6: …
=> fix: make layout generator produce correct paths on Windows (#412)

CHANGELOG.md
Somehow, in 322efe3d55ad43dd417f441095ccb4f15dc1c884, all newlines got converted to carriage returns. Tools such as Git consider such line endings to be invalid: see how GitHub renders the entire file on a single line in "Blame" view.
I doubt that the changelog generator did this, because [it uses newlines](https://github.com/liferay/liferay-npm-tools/blob/19cddf8eb8d736c0bad5eb9ab8bddfb4423865f8/packages/liferay-changelog-generator/src/index.js#L207
).
Probably just a misconfigured editor or some other tool.
Note line count before (0), fix using `tr`, and line count after (501):
wc CHANGELOG.md
0    2528   41440 CHANGELOG.md
cat CHANGELOG.md | tr '\r' '\n' > tmp.md
mv tmp.md CHANGELOG.md
wc CHANGELOG.md
501    2528   41440 CHANGELOG.md
=> style: fix mangled changelog

CHANGELOG.md
Just making sure that these two pulls to the generator are good before publishing a new release:
- https://github.com/liferay/liferay-npm-tools/pull/398
- https://github.com/liferay/liferay-npm-tools/pull/399
So this is just a test of those, done with:
../liferay-npm-tools/packages/liferay-changelog-generator/bin/liferay-changelog-generator.js \
--from=v8.0.0 \
--to=v9.5.0 \
--version=v9.5.0 \
--regenerate
Note that I only regenerated the v8+ section of the changelog, to minimize the chaos.
=> docs: update CHANGELOG with new version of liferay-changelog-generator

CHANGELOG.md
This Markdown was extracted from the commit message in a2bd807b8031ed6, but we can fix it manually; seeing as we won't be regenerating the changelog but rather will be appending from now on, we can expect the fix to be preserved.
Just a reminder to anybody that sees this, in order to keep the changelog quality high and free from errors like this, we should be accepting the proposed merge commit generated by GitHub when we merge in PRs and avoid hand-editing.
=> docs: fix bad Markdown syntax

package.json, packages/generator-liferay-theme/package.json, packages/liferay-theme-mixins/package.json, packages/liferay-theme-tasks/package.json, scripts/release-snapshot.js, scripts/util/report.js, scripts/util/run.js, update-package-versions-config.js, yarn.lock
I'm copying the release-snapshot script from JS Toolkit to be able to automate snapshot releases and make the process less error prone.
=> chore: Add release-snapshot script

packages/liferay-theme-tasks/plugin/tasks/deploy.js
See #457 for a description of what this fixes.
=> fix: #457 gulp deploy fails in Windows

README.md
Added blank lines as well to make the different versions more obvious.
Not currently mentioning that we're going to "deprecate" v9 as there is no great urgency for people to move off it (unless they want to use Node v12), but at some point we should mention that.
=> docs: mention versions > v9 in the compatibility table

.yarnrc
As described [here](https://github.com/liferay/liferay-js-themes-toolkit/issues/473#issuecomment-614038031), this change, together with the corresponding PR to the 9.x branch, will ensure that only non-prerelease `master` (ie. v10) release get the "latest" tag on NPM.
=> feat: automatically tag 8.x releases with "maintenance" tag

.yarnrc
As described [here](https://github.com/liferay/liferay-js-themes-toolkit/issues/473#issuecomment-614038031), this, together with [the corresponding PR to the 8.x branch](https://github.com/liferay/liferay-js-themes-toolkit/pull/474), will ensure that only non-prerelease `master` (ie. v10) release get the "latest" tag on NPM.
Closes: https://github.com/liferay/liferay-js-themes-toolkit/issues/473
=> feat: automatically tag 9.x releases with "maintenance" tag

CONTRIBUTING.md
See commit.
No need to send equivalent PR for v8 as it has been updated before.
=> docs: update release process after v10 release

README.md
This is a backport of [\#470](https://github.com/liferay/liferay-js-themes-toolkit/pull/470).
Idea is to make clear when/why to use v7, v8, v9 or v10. Backporting it here in case somebody gets onto this branch via a tag or some release notes.
=> docs: backport compatibility info changes to 9.x

README.md
This is a backport of [\#470](https://github.com/liferay/liferay-js-themes-toolkit/pull/470).
Idea is to make clear when/why to use v7, v8, v9 or v10. Backporting it here in case somebody gets onto this branch via a tag or some release notes.
=> docs: backport compatibility info changes to 8.x

.yarnrc, CONTRIBUTING.md
Hey @izaera, figure we might as well make these improvements while how all this works is still fresh in our minds. Let me know what you think, especially with respect to use a generic "-pre" prefix for any prerelease.
---
Given our experience today cutting releases of v10 and v9.5.1, we spent some time looking at the effects of `.yarnrc` files, dist tags, and the behavior of `yarn version` with various different flags:
https://github.com/liferay/liferay-js-themes-toolkit/issues/473
Armed with that knowledge, I think we should make some updates to the documentation here:
- Make it clear that `yarn changelog` must run from a *package* directory, not from the top level ("project" is ambiguous; is it the repo, or a package?).
- Drop "project-name" from version number because …
=> docs: update CONTRIBUTING.md

CONTRIBUTING.md
We were missing the tag because it was kind of hidden inside the next step, which we removed in the previous PR because it wasn't needed any more.
Note that I have added a command to push the exact tag directly to upstream. 
I tried in v9.5.1 release doing `git push upstream 9.x --follow-tags` to make everything in one step but only managed to:
1) Push a stale `generator-liferay-theme/vv10.0.0-alpha.1` that I had in local (I have fixed the disaster upstream; no need to worry).
2) Don't get the `v9.5.1` tag pushed upstream
:shrug: 
Thus, I decided that pushing the tag explicitly is safer for the future...
**Doubt: I'm unsure if pushing the tag will push the chore commit upstream too. If that was the case, the second push would be superfluous...** :point_left: @wincent Any idea?
=> docs: fix incomplete release process

packages/liferay-theme-tasks/theme/lib/getBaseThemeDependencies.js
Inheritance of themes is being applied in reverse order. This PR fixes that.
=> fix: #482 reverse themes inheritance order

packages/generator-liferay-theme/generators/app/index.js, packages/generator-liferay-theme/generators/import/index.js, packages/generator-liferay-theme/generators/layout/index.js, packages/generator-liferay-theme/generators/themelet/index.js, packages/generator-liferay-theme/lib/utils/config.js, packages/generator-liferay-theme/lib/utils/promptWithConfig.js
I have cherry-picked the `promptWithConfig` method from v10 and adapted it to v8. It mostly resembles the same code in v10 but it's a bit different due to the refactors I did in v10.
I have tested the `--config` option manually and compared its output to that of the interactive generator. All seems right. 
However, because this will be tested by the blade team when using it, I have not been very exhaustive in my tests. The plan is releasing an alpha version and then, when the blade team gives the OK, release the final minor version upgrade.
=> feat: #466 backport batch mode (--config) to v8

packages/generator-liferay-theme/generators/facet-theme/index.js, packages/generator-liferay-theme/generators/layout/standalone-layout.js, packages/generator-liferay-theme/lib/util.js
`gulp init` for layout projects was running the `liferay-theme-tasks` associated to themes. This caused the deployment directory to be written in `liferay-theme.json` instead of `liferay-plugin.json` making `gulp deploy` fail later.
Of course, the fix has been tested. Following the steps described in the issue.
=> fix: #445 gulp init failure

packages/liferay-theme-tasks/lib/project/index.js, packages/liferay-theme-tasks/theme/tasks/build/compile-css.js
Support yarn workpaces in font-awesome enabled projects by simply adding the
workspace's node_modules folder to the SASS include paths.
=> fix: #495 support yarn workspaces

packages/liferay-theme-tasks/lib/prompts/__tests__/extend_prompt.test.js, packages/liferay-theme-tasks/lib/prompts/extend_prompt.js
As described in the related issue<sup>[1]</sup>, we have some fragile code in here that uses `__filePath__` property to tag local installs. That is, if we extend a "foo-themelet", it will normally come from an NPM package of the same name, but users can choose to extend a themelet from some local path instead (eg. "~/themelets/my-fancy-themelet"), and in those cases we will use this `__filePath__` property to pass along metadata between the Yeoman prompt and the tasks which actually do the work.
We "reduce" package information that comes in from the Yeoman prompt ("reduce" is a terrible name for it; what it means is we strip out fields that we don't want to be written into the package.json), one aspect of which is rewriting `__filePath__` to `path`.
And then, when we install packages, we …
=> fix(tasks): actually extend local themelets (#499)

packages/liferay-theme-deps-7.0/.yarnrc, packages/liferay-theme-deps-7.1/.yarnrc
We have a .yarnrc at the top level to stop 8.x releases from getting the "latest" tag in NPM (likewise on the 9.x branch; we only want 10.x — ie. master — to get the "latest" tags).
But for the two "theme-deps" packages, it's fine for them to have a "latest" tag. Otherwise people will keep getting 8.1.2, which is the last version we released with a latest tag, and never get anything newer.
Not a big deal, of course, because there are no real changes after 8.1.2 anyway, but it still seems desirable that we don't have an NPM versions page that looks like this:
- 8.1.2 ... latest
- 8.2.2 ... maintenance
I'll manually get rid of the maintenance tags on these packages using:
npm dist-tag rm liferay-theme-deps-7.0 maintenance
npm dist-tag rm liferay-theme-deps-7.1 maintenance
And make sure the …
=> chore: don't tag theme-deps packages as "maintenance"

packages/liferay-theme-tasks/theme/tasks/watch.js
LPS-121779 Fix race condition on liferay-theme-tasks gulp watch task 'Cannot read property 'path' of undefined' when changes saved in short time, multiple times.
=> fix: [TS] LPS-121779 race condition on liferay-theme-tasks gulp watch task
